apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mwjobs.com.abid.crd.job
spec:
  preserveUnknownFields: false
  group: com.abid.crd.job
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: mwjobs
    singular: mwjob
    kind: MWJob
    shortNames:
      - mw
      - mws
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            masterTemplate:
              type: object
              properties:
                spec:
                  type: object
            workerTemplate:
              type: object
              properties:
                spec:
                  type: object
