apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "mwjobs.com.abid.crd.job"
spec:
  group: "com.abid.crd.job"
  version: "v1"
  scope: "Namespaced"
  names:
    plural: "mwjobs"
    singular: "mwjob"
    kind: "MWJob"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      propertirs:
        spec:
          required: ["masterTemplate", "workerTemplate"]
          propertirs:
            masterTemplate:
              type: "object"
              properties:
                metadata:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                    annotations:
                      type: "object"
                      additionalProperties:
                        type: "string"
                spec:
                  type: "object"
            workerTemplate:
              type: "object"
              properties:
                metadata:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                    annotations:
                      type: "object"
                      additionalProperties:
                        type: "string"
                spec:
                  type: "object"
