/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.19.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.abid.k8.crd.model;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * MWJobSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-25T08:35:57.748Z[Etc/UTC]")
public class MWJobSpec {
    public static final String SERIALIZED_NAME_MASTER_TEMPLATE = "masterTemplate";
    @SerializedName(SERIALIZED_NAME_MASTER_TEMPLATE)
    private MWJobSpecMasterTemplate masterTemplate;

    public static final String SERIALIZED_NAME_WORKER_TEMPLATE = "workerTemplate";
    @SerializedName(SERIALIZED_NAME_WORKER_TEMPLATE)
    private MWJobSpecMasterTemplate workerTemplate;


    public MWJobSpec masterTemplate(MWJobSpecMasterTemplate masterTemplate) {

        this.masterTemplate = masterTemplate;
        return this;
    }

    /**
     * Get masterTemplate
     *
     * @return masterTemplate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public MWJobSpecMasterTemplate getMasterTemplate() {
        return masterTemplate;
    }


    public void setMasterTemplate(MWJobSpecMasterTemplate masterTemplate) {
        this.masterTemplate = masterTemplate;
    }


    public MWJobSpec workerTemplate(MWJobSpecMasterTemplate workerTemplate) {

        this.workerTemplate = workerTemplate;
        return this;
    }

    /**
     * Get workerTemplate
     *
     * @return workerTemplate
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public MWJobSpecMasterTemplate getWorkerTemplate() {
        return workerTemplate;
    }


    public void setWorkerTemplate(MWJobSpecMasterTemplate workerTemplate) {
        this.workerTemplate = workerTemplate;
    }


    @Override
    public boolean equals(Object o) {
        return EqualsBuilder.reflectionEquals(this, o);
    }

    @Override
    public int hashCode() {
        return HashCodeBuilder.reflectionHashCode(this);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MWJobSpec {\n");
        sb.append("    masterTemplate: ").append(toIndentedString(masterTemplate)).append("\n");
        sb.append("    workerTemplate: ").append(toIndentedString(workerTemplate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

